server:
  port: 8889
spring:
  application:
    name: config-server-cadastro-fornecedor
  cloud:
    config:
      server:
        git:
          uri: https://github.com/scheronlini/config-server-cadastro-fornecedor-git
          defaultLabel: main
          search-paths:
            - 'cadastro-fornecedor*'
