server:
 port: 8000
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
spring:
 application:
  name: cadastro-fornecedor
 config:
  import:
   - optional:configserver:http://localhost:8889/
 cloud:
  config:
   profile: prod
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cadastro_fornecedor?useTimezone=true&serverTimezone=UTC
  username: root
  password: yl6kj8a8
 jpa:
  openInView: true
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
 flyway:
  url: jdbc:mysql://localhost:3306/cadastro_fornecedor?useTimezone=true&serverTimezone=UTC
  user: root
  password: yl6kj8a8
 sleuth:
  sampler:
   probability: 1.0
springdoc:
 showActuator: true
 apiDocs:
  path: cadastro-fornecedor/v3/api-docs

