spring:
 datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS fornecedor
  username: sa
  password:
 jpa:
  openInView: true
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.H2Dialect



