server:
  port: 8888
spring:
  application:
    name: config-server-adm
  cloud:
    config:
      server:
        git:
          uri: https://github.com/scheronlini/config-server-adm
          defaultLabel: main
          search-paths:
            - 'endereco*'


