spring:
 application:
  name: enderecos
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/enderecos?useTimezone=true&serverTimezone=UTC
  username: root
  password: yl6kj8a8
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
 flyway:
  url: jdbc:mysql://localhost:3306/
  schemas: enderecos
  user: root
  password: yl6kj8a8